Create gremlin docker
codacy/alpine-gremlin pull request #1
Opened 2018-08-02 16:20 UTC by jllopes

2018-08-02 16:30 UTC, machadoit requested changes

2018-08-02 16:30 UTC, machadoit commented on .circleci/config.yml
> +      - build
Add newline at the end of the file

2018-08-02 16:30 UTC, machadoit commented on Dockerfile
> +    && /bin/bash ./validate.sh
you don't need ./, you can just /bin/bash validate.sh

2018-08-02 16:30 UTC, machadoit commented on grapeConfig.xml
> +</ivysettings>
newline at the end

2018-08-02 16:30 UTC, machadoit commented on validate.sh
> +
A echo at the begging wouldn't hurt, like echo "====> Checking if docker build successfully" or something like that

2018-08-02 20:01 UTC, rtfpessoa commented
@jllopes seems like you did not

2018-08-03 08:28 UTC, rtfpessoa submitted a review, later dismissed

2018-08-03 08:35 UTC, machadoit submitted a review, later dismissed

2018-08-03 11:02 UTC, machadoit approved these changes

2018-08-03 12:57 UTC, rtfpessoa approved these changes

2018-08-03 12:57 UTC, merged